# Este arquivo YAML define um Headless Service chamado headless-service para fornecer descoberta de DNS para os Pods rotulados como app: stateful-app.
# Vamos analisar cada seção:

apiVersion: v1  # Indica a versão da API Kubernetes utilizada neste recurso YAML.
kind: Service   # Especifica que estamos definindo um Service.

metadata:       # Contém informações sobre o objeto, como o nome.
  name: headless-service  # Define o nome do Service como headless-service.

spec:           # Contém as especificações para o Service.
  clusterIP: None  # Configura o Service como Headless, sem IP de Cluster.

  selector:     # Define os Pods que este Service vai direcionar. Neste caso, ele seleciona todos os Pods com o rótulo app: stateful-app.
    app: stateful-app

  ports:        # Especifica as portas utilizadas pelo Service.
    - protocol: TCP     # Indica o protocolo de comunicação (TCP neste caso).
      port: 80          # Define a porta no Service.
      targetPort: 8080   # Mapeia a porta no Pod para a qual o tráfego será encaminhado.
